-- =====================================================================
-- JENZY THRIFTS — Supabase database setup
-- ---------------------------------------------------------------------
-- HOW TO RUN: Supabase dashboard → SQL Editor → New query →
--             paste this whole file → Run.
-- Safe to run more than once (it only adds what is missing).
-- =====================================================================


-- ---------------------------------------------------------------------
-- 1) PRODUCTS
--    Each size in "sizes" = one available pair.
--    When a pair is ordered its size is removed automatically.
--    When no sizes are left the product becomes "Sold".
-- ---------------------------------------------------------------------
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  name text not null,
  brand text,
  category text,
  condition text,
  price integer not null,
  original_price integer default 0,
  gender text default 'Unisex',          -- Men / Women / Unisex / Kids
  color text,
  sizes text[] default '{}',
  status text default 'Active',          -- Active | Draft | Sold
  tag text,
  description text,
  images text[] default '{}'
);

alter table public.products add column if not exists updated_at timestamptz default now();

alter table public.products enable row level security;

-- Visitors can see Active and Sold products (never Drafts).
-- Nobody can change products from the browser: the admin panel
-- saves through the secure server (/api/admin) instead.
drop policy if exists "Public can read products" on public.products;
drop policy if exists "Public can read listed products" on public.products;
create policy "Public can read listed products"
  on public.products for select
  using (status in ('Active', 'Sold'));

-- Remove any old "anyone can write" policies if you added them while testing
drop policy if exists "Anyone can insert products" on public.products;
drop policy if exists "Anyone can update products" on public.products;
drop policy if exists "Anyone can delete products" on public.products;

-- Live stock updates on the website (Supabase Realtime)
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables
                     where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'products') then
    alter publication supabase_realtime add table public.products;
  end if;
end $$;


-- ---------------------------------------------------------------------
-- 2) ORDERS  (private — only the secure server can read/write them)
-- ---------------------------------------------------------------------
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no bigint generated by default as identity (start with 1001) unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_uid text not null,                 -- Firebase user id
  user_email text,
  customer_name text not null,
  phone text not null,
  address text not null,
  city text not null,
  notes text,
  payment_method text not null default 'COD',
  items jsonb not null default '[]',      -- [{product_id, name, brand, size, price, image}]
  subtotal integer not null default 0,
  discount integer not null default 0,
  coupon text,
  delivery_fee integer not null default 0,
  total integer not null default 0,
  status text not null default 'Pending'
    check (status in ('Pending', 'Confirmed', 'Shipped', 'Delivered', 'Cancelled')),
  status_history jsonb not null default '[]'
);

create index if not exists orders_user_uid_idx on public.orders (user_uid);
create index if not exists orders_created_at_idx on public.orders (created_at desc);

alter table public.orders enable row level security;   -- no policies = no browser access
revoke all on public.orders from anon, authenticated;


-- ---------------------------------------------------------------------
-- 3) CONTACT MESSAGES (the "Send Us a Message" form)
--    Visitors can send; only the admin panel can read.
-- ---------------------------------------------------------------------
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz default now(),
  name text not null check (char_length(name) between 1 and 100),
  email text not null check (char_length(email) between 3 and 150),
  phone text check (phone is null or char_length(phone) <= 30),
  subject text check (subject is null or char_length(subject) <= 100),
  message text not null check (char_length(message) between 1 and 2000),
  user_uid text,
  is_read boolean default false
);

alter table public.messages add column if not exists is_read boolean default false;
alter table public.messages enable row level security;

drop policy if exists "Anyone can send a message" on public.messages;
create policy "Anyone can send a message"
  on public.messages for insert
  to anon, authenticated
  with check (true);


-- ---------------------------------------------------------------------
-- 4) PLACE ORDER — runs as ONE transaction:
--    locks each product, checks the size is still available,
--    uses the REAL price from the database, removes the size,
--    marks the product Sold when empty, then saves the order.
--    Two people can never buy the same pair.
-- ---------------------------------------------------------------------
create or replace function public.place_order(
  p_user_uid text,
  p_user_email text,
  p_customer_name text,
  p_phone text,
  p_address text,
  p_city text,
  p_notes text,
  p_items jsonb,
  p_coupon text,
  p_discount_percent integer,
  p_delivery_fee integer,
  p_free_delivery_min integer
) returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item jsonb;
  v_product public.products%rowtype;
  v_size text;
  v_remaining text[];
  v_items jsonb := '[]'::jsonb;
  v_subtotal integer := 0;
  v_discount integer := 0;
  v_after integer;
  v_fee integer;
  v_order public.orders;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'EMPTY_CART';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_size := v_item->>'size';

    select * into v_product
      from public.products
     where id = (v_item->>'product_id')::uuid
     for update;

    if not found or v_product.status <> 'Active' then
      raise exception 'UNAVAILABLE:%', coalesce(v_product.name, 'An item');
    end if;

    if v_size is null or not (v_size = any(v_product.sizes)) then
      raise exception 'SIZE_UNAVAILABLE:% (size %)', v_product.name, coalesce(v_size, '?');
    end if;

    v_remaining := array_remove(v_product.sizes, v_size);

    update public.products
       set sizes = v_remaining,
           status = case when cardinality(v_remaining) = 0 then 'Sold' else status end,
           updated_at = now()
     where id = v_product.id;

    v_items := v_items || jsonb_build_array(jsonb_build_object(
      'product_id', v_product.id,
      'name', v_product.name,
      'brand', v_product.brand,
      'size', v_size,
      'price', v_product.price,
      'image', coalesce(v_product.images[1], '')
    ));
    v_subtotal := v_subtotal + v_product.price;
  end loop;

  v_discount := (v_subtotal * greatest(least(coalesce(p_discount_percent, 0), 100), 0)) / 100;
  v_after := v_subtotal - v_discount;
  v_fee := case when v_after >= coalesce(p_free_delivery_min, 0) then 0 else greatest(coalesce(p_delivery_fee, 0), 0) end;

  insert into public.orders (
    user_uid, user_email, customer_name, phone, address, city, notes,
    items, subtotal, discount, coupon, delivery_fee, total, status, status_history
  ) values (
    p_user_uid, p_user_email, p_customer_name, p_phone, p_address, p_city, nullif(p_notes, ''),
    v_items, v_subtotal, v_discount, nullif(p_coupon, ''), v_fee, v_after + v_fee, 'Pending',
    jsonb_build_array(jsonb_build_object('status', 'Pending', 'at', now(), 'by', 'customer'))
  )
  returning * into v_order;

  return v_order;
end;
$$;


-- ---------------------------------------------------------------------
-- 5) CHANGE ORDER STATUS — cancelling puts the pairs back in stock.
-- ---------------------------------------------------------------------
create or replace function public.set_order_status(
  p_order_id uuid,
  p_status text,
  p_by text
) returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
  v_item jsonb;
begin
  if p_status not in ('Pending', 'Confirmed', 'Shipped', 'Delivered', 'Cancelled') then
    raise exception 'BAD_STATUS';
  end if;

  select * into v_order from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'ORDER_NOT_FOUND';
  end if;

  if v_order.status = p_status then
    return v_order;
  end if;

  if v_order.status = 'Cancelled' then
    raise exception 'ALREADY_CANCELLED';
  end if;

  -- Cancelling: return every pair to stock
  if p_status = 'Cancelled' then
    for v_item in select * from jsonb_array_elements(v_order.items)
    loop
      update public.products
         set sizes = case when (v_item->>'size') = any(sizes) then sizes
                          else array_append(sizes, v_item->>'size') end,
             status = case when status = 'Sold' then 'Active' else status end,
             updated_at = now()
       where id = (v_item->>'product_id')::uuid;
    end loop;
  end if;

  update public.orders
     set status = p_status,
         updated_at = now(),
         status_history = status_history || jsonb_build_array(
           jsonb_build_object('status', p_status, 'at', now(), 'by', coalesce(p_by, 'admin')))
   where id = p_order_id
  returning * into v_order;

  return v_order;
end;
$$;

-- Only the secure server (service role) may run these functions
revoke all on function public.place_order(text, text, text, text, text, text, text, jsonb, text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.set_order_status(uuid, text, text) from public, anon, authenticated;
grant execute on function public.place_order(text, text, text, text, text, text, text, jsonb, text, integer, integer, integer) to service_role;
grant execute on function public.set_order_status(uuid, text, text) to service_role;


-- ---------------------------------------------------------------------
-- 6) IMAGE STORAGE BUCKET (public, so product photos can be shown)
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;
